export enum ParameterEnum {
    Vertices = "Vertices",
    Probability = "Probability",
    Edges = "Edges",
    StepCount = "StepCount",
    EvolutionStepCount = "EvolutionStepCount",
    Omega = "Omega",
    PermanentDistribution = "PermanentDistribution",
    TracingStepIncrement = "TracingStepIncrement",
    ProbabilityMax = "ProbabilityMax",
    ProbabilityDelta = "ProbabilityDelta",
    InitialActivationProbability = "InitialActivationProbability",
    DeactivationSpeed = "DeactivationSpeed",
    ActivationSpeed = "ActivationSpeed",
    ActivationStepCount = "ActivationStepCount",
    FitnessDensityFunction = "FitnessDensityFunction",
    BranchingIndex = "BranchingIndex",
    Mu = "Mu",
    Level = "Level",
    ZeroLevelNodesCount = "ZeroLevelNodesCount",
    Alpha = "Alpha",
    BlocksCount = "BlocksCount",
    MakeConnected = "MakeConnected"
}
